spring:
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/clairvoyance?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
        username: root
        password: asd
    mvc:
        static-path-pattern: /static/**

    thymeleaf:
        prefix:
        classpath: /templates/**
        cache: false
    resources:
        static-locations: classpath:/static/, classpath:/static/images/
    cache: false
mybatis:
    type-aliases-package: com.cav.clairvoyance.domain
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl